apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        imagePullPolicy: Always