{
 "title": "Systems OverView",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(system_uptime,host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available hosts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "100 * sum(up)/count(up)" }
   ]
  },
  {
   "title": "$host",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~'$host:9273',job='linux_hosts'}"
    }
   ]
  },
  {
   "title": "Load Average 1s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "repeat": "host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}/system_n_cpus{host=~\"$host\"}*100"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "repeat": "host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\",host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "repeat": "host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "repeat": "host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "swap_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "max disk usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "repeat": "host",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(disk_used_percent{host=~\"$host.*\", path!=\"/boot\"})"
    }
   ]
  },
  {
   "title": "max disk queue",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(diskio_iops_in_progress{host=~\"$host.*\"})"
    }
   ]
  },
  {
   "title": "max net errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(net_err_in{host=\"$host\"}[5m]) or irate(net_err_out{host=\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
   "repeat": "host",
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_temp{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_throttled{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~'$host:9273',job='linux_hosts'}"
    }
   ]
  },
  {
   "title": "Load Average 1s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}/system_n_cpus{host=~\"$host\"}*100"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\",host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "swap_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "max disk usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(disk_used_percent{host=~\"$host.*\", path!=\"/boot\"})"
    }
   ]
  },
  {
   "title": "max disk queue",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(diskio_iops_in_progress{host=~\"$host.*\"})"
    }
   ]
  },
  {
   "title": "max net errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(net_err_in{host=\"$host\"}[5m]) or irate(net_err_out{host=\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_temp{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_throttled{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~'$host:9273',job='linux_hosts'}"
    }
   ]
  },
  {
   "title": "Load Average 1s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}/system_n_cpus{host=~\"$host\"}*100"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\",host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "swap_used_percent{host=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "max disk usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(disk_used_percent{host=~\"$host.*\", path!=\"/boot\"})"
    }
   ]
  },
  {
   "title": "max disk queue",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(diskio_iops_in_progress{host=~\"$host.*\"})"
    }
   ]
  },
  {
   "title": "max net errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(net_err_in{host=\"$host\"}[5m]) or irate(net_err_out{host=\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_temp{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_throttled{host=\"$host\"}"
    }
   ]
  }
 ]
}