{
 "title": "System",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(cpu_usage_idle,host)"
   },
   {
    "name": "disk",
    "query": "query_result(diskio_read_bytes{host=\"$host\"})"
   },
   {
    "name": "mount",
    "query": "query_result(disk_free{host=\"$host\"})"
   },
   {
    "name": "interface",
    "query": "query_result(net_bytes_recv{host=\"$host\"})"
   }
  ]
 },
 "panels": [
  { "title": "RPI-HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "HZ" }
   ],
   "targets": [
    {
     "expr": "rpi_freq{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius", "label": "'C" }
   ],
   "targets": [
    {
     "expr": "rpi_temp{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Voltage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "volt", "label": "V" }
   ],
   "targets": [
    {
     "expr": "rpi_voltage{host=\"$host\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "guest"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "guest_nice"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "softirq"
    },
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",host=\"$host\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_buffered{host=\"$host\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_cached{host=\"$host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_free{host=\"$host\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=\"$host\"}",
     "legendFormat": "short"
    },
    {
     "expr": "system_load5{host=\"$host\"}",
     "legendFormat": "mid"
    },
    {
     "expr": "system_load15{host=\"$host\"}",
     "legendFormat": "long"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{host=\"$host\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "processes_paging{host=\"$host\"}",
     "legendFormat": "paging"
    },
    {
     "expr": "processes_running{host=\"$host\"}",
     "legendFormat": "running"
    },
    {
     "expr": "processes_sleeping{host=\"$host\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "processes_stopped{host=\"$host\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "processes_zombies{host=\"$host\"}",
     "legendFormat": "zombie"
    }
   ]
  },
  {
   "title": "Process forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(kernel_processes_forked{host=\"$host\"}[5m])",
     "legendFormat": "fork rate"
    }
   ]
  },
  { "title": "File system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Used space on $mount",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\",path=\"$mount\"}"
    }
   ]
  },
  {
   "title": "Used inodes on $mount",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * disk_inodes_used{host=\"$host\",path=\"$mount\"} / disk_inodes_total{host=\"$host\",path=\"$mount\"}"
    }
   ]
  },
  {
   "title": "Usage on $mount partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_used{host=\"$host\",path=\"$mount\"}",
     "legendFormat": "used"
    },
    {
     "expr": "disk_free{host=\"$host\",path=\"$mount\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Inodes on $mount partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "disk_inodes_used{host=\"$host\",path=\"$mount\"}",
     "legendFormat": "used"
    },
    {
     "expr": "disk_inodes_free{host=\"$host\",path=\"$mount\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Throughput on $disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_read_bytes{host=\"$host\",name=\"$disk\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(diskio_write_bytes{host=\"$host\",name=\"$disk\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Operations on $disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_reads{host=\"$host\",name=\"$disk\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(diskio_writes{host=\"$host\",name=\"$disk\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Throughput on $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(net_bytes_recv{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(net_bytes_sent{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packets on $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(net_packets_recv{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(net_packets_sent{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Errors on $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(net_err_in{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(net_err_out{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Dropped packets on $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(net_drop_in{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(net_drop_out{host=\"$host\",interface=\"$interface\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  },
  { "title": "Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 54 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "swap_used_percent{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "swap_used{host=\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "swap_free{host=\"$host\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 54 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(swap_in{host=\"$host\"}[5m])/300",
     "legendFormat": "in"
    },
    {
     "expr": "irate(swap_out{host=\"$host\"}[5m])/300",
     "legendFormat": "out"
    }
   ]
  }
 ]
}